company:
  name: "Document Q&A System"
  primary_color: "#2E86AB"
  secondary_color: "#A23B72"
  logo_url: null

system:
  supported_formats: ["pdf", "docx", "txt"]
  max_file_size: 50  # MB
  batch_size: 5
  max_workers: 3
  
# Optional features
features:
  visual_detection: true
  batch_vlm_processing: true
  analytics: true
  chat_history: true

# API Keys (if needed)
api:
  google_api_key: Gemini_API_KEY
  huggingface_api_key: HuggingFace_API_KEY
